import * as mongoose from 'mongoose';
export const productSchema = new mongoose.Schema({
  Itm_id: String,
  Itm_BarCode: String,
  Itm_Cat_ID: String,
  Itm_Cat_ID2: String,
  Itm_Cat_ID3: String,
  Itm_Cat_ID4: String,
  Itm_Cat_ID5: String,
  Itm_Desc1: String,
  Itm_Desc2: String,
  Itm_Tax: Number,
  Itm_Sls_Unt: String,
  Itm_Price: Number,
  Itm_Price2: Number,
  Itm_Memo: String,
  Itm_Size: String,
  Itm_Component: String,
  Itm_Method: String,
  Itm_Method2: String,
  Itm_Method3: String,
  Itm_Date: Date,
  Itm_Char: String,
  Itm_Change: Number,
  Itm_age: Number,
  Itm_Pack: Number,
  Itm_Pack_Barcode: String,
  Itm_Pack_Size: String,
  Itm_Cat_Acc: String,
  Itm_CatSub_ID: String,
  Itm_PregCat: String,
  Itm_Price_Pack: Number,
  Itm_Big_Pack: Number,
  Itm_Big_Pack_Barcode: String,
  Itm_Big_Pack_Price: Number,
  Itm_Weight: Number,
  Itm_Member_Price: Number,
  Itm_Max_Per_Slip: Number,
  Itm_Temperature: Number,
  Itm_Warning_Slip: Number,
  Itm_Buyer_Age: Number,
  Itm_Reg_No: String,
  Itm_Avoid_Light: Number,
  Itm_Sale_Pack: Number,
  Itm_Sale_Pack_Price: Number,
  Itm_Memo_Public: String,
  Product_image: mongoose.Schema.Types.Mixed,
});

export interface Product extends Document {
  Itm_id: String;
  Itm_BarCode: String;
  Itm_Cat_ID: String;
  Itm_Cat_ID2: String;
  Itm_Cat_ID3: String;
  Itm_Cat_ID4: String;
  Itm_Cat_ID5: String;
  Itm_Desc1: String;
  Itm_Desc2: String;
  Itm_Tax: Number;
  Itm_Sls_Unt: String;
  Itm_Price: Number;
  Itm_Price2: Number;
  Itm_Memo: String;
  Itm_Size: String;
  Itm_Component: String;
  Itm_Method: String;
  Itm_Method2: String;
  Itm_Method3: String;
  Itm_Date: Date;
  Itm_Char: String;
  Itm_Change: Number;
  Itm_age: Number;
  Itm_Pack: Number;
  Itm_Pack_Barcode: String;
  Itm_Pack_Size: String;
  Itm_Cat_Acc: String;
  Itm_CatSub_ID: String;
  Itm_PregCat: String;
  Itm_Price_Pack: Number;
  Itm_Big_Pack: Number;
  Itm_Big_Pack_Barcode: String;
  Itm_Big_Pack_Price: Number;
  Itm_Weight: Number;
  Itm_Member_Price: Number;
  Itm_Max_Per_Slip: Number;
  Itm_Temperature: Number;
  Itm_Warning_Slip: Number;
  Itm_Buyer_Age: Number;
  Itm_Reg_No: String;
  Itm_Avoid_Light: Number;
  Itm_Sale_Pack: Number;
  Itm_Sale_Pack_Price: Number;
  Itm_Memo_Public: String;
  Product_image: mongoose.Schema.Types.Mixed;
}
