import * as mongoose from 'mongoose';
import { Document } from 'mongoose';
export const sitelistSchema = new mongoose.Schema(
  {
    Site_ID: Number,
    Site_Desc: String,
    Site_Cat: String,
    Site_Cost: Number,
    Site_Dir: String,
    Site_Owner: String,
    Site_Tax: mongoose.Types.Decimal128,
    Site_Address: String,
    Site_Tel: String,
    Site_Start_Date: Date,
    Site_Status: Number,
    Site_Remark: String,
    Site_Target_Sales: Number,
    Site_Target_Point: Number,
    Site_RFee_Percent: Number,
    Site_Point_Rate: Number,
    update_date: Date,
    Site_DB_Dir: String,
    Site_LC: Number,
    Site_Bonus_Rate: Number,
    Site_Bonus_Pop: Number,
    Site_Seller: String,
    Site_Cat_ID: Number,
    Site_Owner_Emp_ID: Number,
    Site_Plan_Type: String,
    Site_Pharmacist_Name: String,
    Site_Pharmacist_Tel: String,
    Site_Pharmacist_Salary: Number,
    Site_Pharmacist_Pay_Type: Number,
    Site_Area1_Emp_ID: Number,
    Site_Area1_Emp_Wage: Number,
    Site_Area2_Emp_ID: Number,
    Site_Area2_Emp_Wage: Number,
    Site_Pharmacist_Bank: Number,
    Site_Pharmacist_AccID: String,
    Site_Bank: Number,
    Site_AccID: mongoose.Types.Decimal128,
    Site_Renter: String,
    Site_Renter_Tel: String,
    Site_Rent_Amt: Number,
    Site_Rent_Pay_Type: Number,
    Site_Rent_Bank: Number,
    Site_Rent_AccID: String,
    Site_Contract_Start: String,
    Site_Contract_End: String,
    Site_Transfer_Day: Number,
    Site_Renter2: String,
    Site_Renter_Tel2: String,
    Site_Rent_Amt2: Number,
    Site_Rent_Bank2: Number,
    Site_Rent_AccID2: String,
    Site_ADSL: String,
    update_user: String,
    Site_License_Type: Number,
    Site_License_ID: String,
    Site_Licensee: String,
    Site_RFee_Percent_Old: Number,
    Site_Property_Tax: Number,
    Site_Signboard_Tax: Number,
    Site_Rent_Tax: Number,
    Site_Rent_Tax_Type: Number,
    Site_Rent_Tax2: Number,
    Site_Rent_Tax2_Type: Number,
    Site_Pharmacist_EmpID: Number,
    area_id: Number,
    Site_Rent_Bank_Branch: String,
    Site_Rent_Bank_Branch2: String,
    Site_Rent_Transfer_Day: Number,
    Site_Pharmacist_No: Number,
    Site_Pharmacist_Email: String,
    Site_Emp_Qty: Number,
    Site_Extra_Emp_Qty: Number,
    Site_Pharmacist_CitizenID: mongoose.Types.Decimal128,
    Site_Latitude: Number,
    Site_Longitude: Number,
    Site_Comp_AccID: mongoose.Types.Decimal128,
    Site_Comp_Person_ID: mongoose.Types.Decimal128,
    Site_Guarantee_Product: Number,
    Site_Guarantee_Diff: Number,
    Site_Quality_Status: Number,
    Site_Collector_Emp_ID: String,
    Site_Width: Number,
    Site_Length: Number,
    Site_Height: Number,
    Site_Transfer_Car: Number,
    Site_Desc2: String,
    Site_Tel2: String,
    Site_Pharmacist_EmpID2: Number,
    Site_Pharmacist_EmpID3: String,
    Site_Pharmacist_Client_Name: String,
    Site_Pharmacist_Client_MacAddr: String,
    Site_Address_Invoice: String,
    Site_Open_Time: String,
    Site_Close_Time: String,
    Site_End_Date: String,
    Site_Mobile: String,
    Site_Renovate: Number,
    row_version: String,
  },
  { versionKey: false },
);

export interface sitelist extends Document {
  Site_ID: number;
    Site_Desc: string;
    Site_Cat: string;
    Site_Cost: number;
    Site_Dir: string;
    Site_Owner: string;
    Site_Tax: mongoose.Types.Decimal128;
    Site_Address: string;
    Site_Tel: string;
    Site_Start_Date: Date;
    Site_Status: number;
    Site_Remark: string;
    Site_Target_Sales: number;
    Site_Target_Point: number;
    Site_RFee_Percent: number;
    Site_Point_Rate: number;
    update_date: Date;
    Site_DB_Dir: string;
    Site_LC: number;
    Site_Bonus_Rate: number;
    Site_Bonus_Pop: number;
    Site_Seller: string;
    Site_Cat_ID: number;
    Site_Owner_Emp_ID: number;
    Site_Plan_Type: string;
    Site_Pharmacist_Name: string;
    Site_Pharmacist_Tel: string;
    Site_Pharmacist_Salary: number;
    Site_Pharmacist_Pay_Type: number;
    Site_Area1_Emp_ID: number;
    Site_Area1_Emp_Wage: number;
    Site_Area2_Emp_ID: number;
    Site_Area2_Emp_Wage: number;
    Site_Pharmacist_Bank: number;
    Site_Pharmacist_AccID: string;
    Site_Bank: number;
    Site_AccID: mongoose.Types.Decimal128;
    Site_Renter: string;
    Site_Renter_Tel: string;
    Site_Rent_Amt: number;
    Site_Rent_Pay_Type: number;
    Site_Rent_Bank: number;
    Site_Rent_AccID: string;
    Site_Contract_Start: string;
    Site_Contract_End: string;
    Site_Transfer_Day: number;
    Site_Renter2: string;
    Site_Renter_Tel2: string;
    Site_Rent_Amt2: number;
    Site_Rent_Bank2: number;
    Site_Rent_AccID2: string;
    Site_ADSL: string;
    update_user: string;
    Site_License_Type: number;
    Site_License_ID: string;
    Site_Licensee: string;
    Site_RFee_Percent_Old: number;
    Site_Property_Tax: number;
    Site_Signboard_Tax: number;
    Site_Rent_Tax: number;
    Site_Rent_Tax_Type: number;
    Site_Rent_Tax2: number;
    Site_Rent_Tax2_Type: number;
    Site_Pharmacist_EmpID: number;
    area_id: number;
    Site_Rent_Bank_Branch: string;
    Site_Rent_Bank_Branch2: string;
    Site_Rent_Transfer_Day: number;
    Site_Pharmacist_No: number;
    Site_Pharmacist_Email: string;
    Site_Emp_Qty: number;
    Site_Extra_Emp_Qty: number;
    Site_Pharmacist_CitizenID: mongoose.Types.Decimal128;
    Site_Latitude: number;
    Site_Longitude: number;
    Site_Comp_AccID: mongoose.Types.Decimal128;
    Site_Comp_Person_ID: mongoose.Types.Decimal128;
    Site_Guarantee_Product: number;
    Site_Guarantee_Diff: number;
    Site_Quality_Status: number;
    Site_Collector_Emp_ID: string;
    Site_Width: number;
    Site_Length: number;
    Site_Height: number;
    Site_Transfer_Car: number;
    Site_Desc2: string;
    Site_Tel2: string;
    Site_Pharmacist_EmpID2: number;
    Site_Pharmacist_EmpID3: string;
    Site_Pharmacist_Client_Name: string;
    Site_Pharmacist_Client_MacAddr: string;
    Site_Address_Invoice: string;
    Site_Open_Time: string;
    Site_Close_Time: string;
    Site_End_Date: string;
    Site_Mobile: string;
    Site_Renovate: number;
    row_version: string;
}
